apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Ap.Collection
  description: |
    Ap.Collection is a service for managing collection of company documents.
  links:
    - title: Website
      url: http://collection
    - title: Documentation
      url: https://collection/docs
  annotations:
    bitbucket.com/project-slug: collection/documents
    backstage.io/techdocs-ref: dir:.
spec:
  type: microservice
  owner: Antiplagiat
  lifecycle: production
