apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Ap.Collection
  description: |
    Ap.Collection is a service for managing collection of company documents.
  links:
    - title: Website
      url: http://collection
    - title: Documentation
      url: https://collection/docs
  tags:
    - C#
spec:
  type: service
  owner: alem
  lifecycle: production
  dependsOn:
    - resource:default/collection-db
  providesApis:
    - collection-private-api
