apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: collection-private-api
  description: Private API interface
spec:
  type: openapi
  lifecycle: production
  owner: alem
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Collection Private API
      license:
        name: MIT
    servers:
      - url: http://collection
    paths:
      /documents:
      "get": {
        "tags": [
          "DemoChecks"
        ],
        "summary": "Получить документы.",
        "parameters": [
          {
            "name": "fromDate",
            "in": "path",
            "description": "дата начала промежутка.",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
              }
            }
          }
        }
      }
          
