apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: collection-private-api
  description: Private API interface
spec:
  type: openapi
  lifecycle: production
  owner: alem
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Collection Private API
      license:
        name: MIT
    servers:
      - url: http://collection
    paths:
      /artists:
        get:
          summary: List all artists          
